# Site settings
title: Blue Button Dashboard
description: > # this means to ignore newlines until "baseurl:"
  Blue Button Dashboard
baseurl: "/dashboard"
url: "http://bluebuttontoolkit.healthit.gov"

# Header
header:
  logo_text: Blue Button
  logo_img: logo.svg
  # nav:
  #   - text: Article
  #     link: /example-article

# Edit pages
edit_page:
  # enabled: true  # Enabled by default for pages and posts
  text: "Edit this page »"
  github:
    author: blue-button
    repo:   dashboard
    branch: gh-pages

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [hard_wrap, tables]

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: template/page
  - scope:
      path: ""
      type: posts
    values:
      layout: template/post
